print('{:=^21}'.format(' Desafio 7 '))
n1 = float(input('Digite a nota do primeiro bimestre: '))
n2 = float(input('Digite a nota do segundo bimestre: '))
n3 = float(input('Digite a nota do terceiro bimestre: '))
n4 = float(input('Digite a nota do quarto bimestre: '))
print('A sua média é {}'.format((n1 + n2 + n3 + n4) / 4))
